naurffxiv/naurffxiv

README.md
This commit adds a command to install react-router-dom, which enables the usage of the <Link> component. This component allows for routing to other pages in the website.
Ticket: NAUR-7
=> NFC: Update readme to install react router

naurffxiv/src/components/NavBar/NavBar.js
Ticket: NAUR-62
- Removed theme switch functionality from desktop and narrow resolutions
- Repositioned hamburger menu to replace theme switch location on narrow resolutions
Note:
Running `make start` required installation of the "remark-frontmatter" npm package to run site locally
Theme switch code remains in the codebase for potential future use - only the button has been removed from the layout
=> updated hamburger menu placement

naurffxiv/src/app/constants.js, naurffxiv/src/components/Homepage/Hero.js, naurffxiv/tailwind.config.js
Ticket: NAUR-90
Ticket: NAUR-92
There's a single pixel line on certain browsers due to the way `background-position: center;` is implemented on different browsers (i think), I've made the linear gradient a separate div from the image to work around this
I've also added urls to the cards in the homepage
=> Fix pixel line bug and add urls to homepage cards

naurffxiv/src/components/Mdx/QuickLinks.js
Ticket: NAUR-107
The clickable area of the links in the quick links section is smaller than the style is. This PR fixes that and makes the entire area clickable
=> Make quick links' links entire area clickable

naurffxiv/src/components/Homepage/OfferingCards.js, naurffxiv/src/components/NavBar/NavBar.js
NAUR-112
This makes the links match the "Ultimates" dropdown color
Also updates wording on homepage while we're at it by request
=> Update navbar items' hover color to match rest

package-lock.json, package.json, src/app/[difficulty]/[[...slug]]/helpers.js, src/components/Mdx/MdxComponents.js, src/rehype/rehypeHeaderSections.js
Ticket: NAUR-121
The ScrollSpy component used to track where the user is currently at on the page currently only tracks header elements. On a section that's taller than the viewport, it will fail since the header element may fall out of view. To fix this, I wrapped every header and its content with a section tag and moved the id from the header to the section, so the underlying IntersectionObserver can keep track of what's on screen.
=> Wrap headers and content with sections

src/app/[difficulty]/[[...slug]]/page.js, src/markdown/testing/_meta.json, src/markdown/testing/page.mdx
Ticket: NAUR-142
This adds a testing page that is only enabled when the `NEXT_PROD` environment variable isn’t set to true. I have already configured the environment variable on the main site, so the testing page should only ever be available locally and on the staging domain.
Testing page is available at `/testing/page`, more can be added if needed
=> Add testing page

src/components/Mdx/MdxComponents.js, src/markdown/testing/page.mdx
Ticket: NAUR-147
This PR makes external links in MDX pages open in a new tab, while keeping internal links on the same tab.
Testing is available at /testing/page
=> Make external links open a new tab in MDX pages

package-lock.json, package.json, src/components/Mdx/Buff.js, src/markdown/testing/buffs.json, src/markdown/testing/page.mdx
Ticket: NAUR-149
Since the phases in buffs.toml could be a decimal (intermissions), it could be an array with integers and floats. Although the newer TOML specification allows for mixed type arrays, the older specification does not. The TOML package we are using right now is outdated, so I've found an alternative package to use instead that follows the most recent specification.
I've additionally added an option to use JSON files instead
=> Use alternative toml package and add json option to Buffs component

src/app/[difficulty]/[[...slug]]/index.js, src/app/[difficulty]/[[...slug]]/mdx.css, src/components/Mdx/ImageModal.js, src/components/Mdx/TableOfContents.js
Ticket: NAUR-150
This PR fixes various bugs with the table of contents and ImageModal.
ToC:
- Properly indent when header is wrapped
- Entire background of a link is now clickable instead of just the text
- Fix a margin bug that sometimes occurs
- Adjust height so that overflow scrolls properly at certain resolutions
ImageModal:
- Remove margin from button
=> Various bug fixes for ToC and ImageModal

src/components/Mdx/QuickLinks.js
Fixes #189 
Some logic was incorrectly placed within a for loop by me. I've moved it out of the loop and should be working fine now.
=> Fix Quick Links not populating for pages with no groups

src/components/Homepage/Hero.js
Fixed the incorrect apostrophe rendering in the main page description
Also corrected the title reference by removing the colon after Final Fantasy XIV, since the base game's name does not include a colon, only expansions like *Final Fantasy XIV: Dawntrail* use it.
=> fix: apostrophe display in Hero section + nit colon

src/app/[difficulty]/[[...slug]]/index.js
This PR adds proper spacing between the top of resource pages and their content. Previously, headings and content were flush with the top of the page, which affected readability and visual hierarchy.
- Added `pt-8` (32px) padding to the top of article elements in resource pages
- This change affects all content pages under the `[difficulty]/[[...slug]]` routes
Before: 
After:
---
Mobile:
Before:
After:
Fixes #187
=> fix: Add Top Padding to Resource Pages

src/app/[difficulty]/[[...slug]]/mdx.css, src/components/Mdx/ImageModal.js
Closes #201 
Currently, image modals are way too small on mobile devices:
This PR makes it so that it takes up the majority of the width like so:
=> Image modal adjustments

src/components/Homepage/FightGuideComponent.js
The color of the homepage cards has been bugging me for a bit now, I eyeballed it a bit and figured this would look a little better than the current color
Before:
After:
Feel free to nitpick more
=> Adjust homepage card color

src/components/NavBar/MobileContentAccordion.jsx, src/components/NavBar/MobileMenu.jsx
Closes #207 
This PR makes it so that items that are children of a section in the mobile navbar (part of the accordion) are counted as separate items in the navbar menu. This makes it so that the overall animations aren't as jarring, e.g when clicking on the parent collapsible "Ultimate", the animation doesn't propagate throughout the entire accordion. (Preview can be seen in the linked issue)
=> Make mobile menu subitems independent of parent

src/components/Mdx/Layout/MobileDrawer.js
Closes #211 
This PR adjusts the position of the mobile quick links drawer button slightly so that it is not cut off on mainstream mobile devices.
=> Adjust position of mobile open quick links drawer button

src/components/Mdx/Elements/Buff.js
Closes #173 
Removes overrides for `description` and `explanation` in the buff component
=> Remove overrides from buff component

src/components/Layout/NavBar/DesktopMenu.jsx
After reviewing other use cases, feel it makes more sense on the mobile view to keep the Home button in the drawer
since from a user perspective, it's more ideal to have a Home button on either side of the screen depending which
hand the user's browsing with.
=> Remove Home button from Desktop

src/config/constants.ts
Kept layout of footer the same, with the removal of the Patreon link.
=> Fix to issue #272: Remove Patreon Link
