- Makefile
- README.md
This commit eases the developing process by just simply running make start instead of changing directories to naurffxiv/src and back again
> Create make start command

- assets/strats/dsr.md
- assets/strats/tea.md
- assets/strats/top.md
- assets/strats/ucob.md
- assets/strats/uwu.md
- naurffxiv/src/app/page.js
- naurffxiv/src/app/uwu.js
Adds markdown files that provide:
- Strats by phase
- General resources
- Video guides and POVs
Removes UWU.js and page.js.
> Add markdown strats files

- .github/workflows/commit-check.yaml
> ci: Add workflow to check for ticket number in commit messages

- .github/workflows/commit-check.yaml
Based off of: https://github.com/naurffxiv/moddingway/pull/150
Ticket: NAUR-13
> Fix ticket validation in PR descriptions

- .github/workflows/tagging.yaml
As we want to see what goes into each release, we should label each commit with a tag to make finding out the release content easier.
Ticket: NAUR-37
> Tag commits

- naurffxiv/src/pages/index.mdx
> Add ultimates section to home page

- naurffxiv/src/pages/ultimates/fru.mdx
> Fix wording of fru page in temp site

- README.md
- naurffxiv/package-lock.json
- naurffxiv/package.json
This commit updates some react and material ui packages,
as well as installing the new material ui icon package.
Ticket: NAUR-23
> Update react packages

- naurffxiv/src/app/globals.css
This commit also removes gradiant coloring in the background.
Ticket: NAUR-5
> Update theme to use official colors

- naurffxiv/src/app/constants.js
> Remove contact us link from nav bar

- naurffxiv/src/app/carousel.js
- naurffxiv/src/app/page.js
- naurffxiv/src/app/theme.js
This commit also adds in theme.js, which makes the theme for the navigation bar.
Ticket: NAUR-45
> Implement image carousel

- naurffxiv/src/pages/ultimates/dsr.mdx
- naurffxiv/src/pages/ultimates/uwu.mdx
Ticket: NAUR-50
Fixes #47 and another typo in the UWU page
> Fix some typos

- naurffxiv/src/pages/ultimates/uwu.mdx
> Add UWU Predation sim to temporary site

- naurffxiv/src/app/page.js
- naurffxiv/src/app/ultimates/dsr/page.js
- naurffxiv/src/app/ultimates/tea/page.js
- naurffxiv/src/app/ultimates/ucob/page.js
- naurffxiv/src/app/ultimates/uwu/page.js
Ticket: NA
Need to fix these things since ESLint is preventing compilation otherwise
> Comply with eslint rules and fix typo

- naurffxiv/package-lock.json
- naurffxiv/package.json
- naurffxiv/src/components/Mdx/MdxContent.jsx
- naurffxiv/src/components/Mdx/MdxLayout.jsx
- naurffxiv/src/pages/resources/dsr.mdx
- naurffxiv/src/pages/resources/fru.mdx
- naurffxiv/src/pages/resources/tea.mdx
- naurffxiv/src/pages/resources/top.mdx
- naurffxiv/src/pages/resources/ucob.mdx
- naurffxiv/src/pages/resources/uwu.mdx
- naurffxiv/tailwind.config.js
> Add basic mdx layout

- naurffxiv/src/components/Footer/Footer.js
- naurffxiv/src/components/Homepage/HomepageContent.js
- naurffxiv/src/components/NavBar/NavBar.js
Ticket: NAUR-66
Simplifies and adds better descriptions in the site
> Update site content

- naurffxiv/src/pages/ultimates/dsr.mdx
- naurffxiv/src/pages/ultimates/fru.mdx
- naurffxiv/src/pages/ultimates/tea.mdx
- naurffxiv/src/pages/ultimates/top.mdx
- naurffxiv/src/pages/ultimates/ucob.mdx
- naurffxiv/src/pages/ultimates/uwu.mdx
Ticket: NAUR-71
- UCoB upkeeping
- Waymark formatting
> Update MDX Content

- naurffxiv/src/components/NavBar/NavBar.js
- naurffxiv/src/components/NavBar/UltimateDropdown.js
Ticket: NAUR-72
- Removes "Guides" as an option
- Left aligns content for better UX
> Update Mobile Hamburger Menu

- naurffxiv/src/pages/ultimates/uwu.mdx
> Update uwu.mdx for temp site

- naurffxiv/package-lock.json
- naurffxiv/package.json
Ticket: NAUR-77
This should fix errors when running `npm install` asking you to use `--force` for `--legacy-peer-deps`
> Update packages and dependencies

- naurffxiv/src/app/page.js
- naurffxiv/src/components/Footer/Footer.js
- naurffxiv/src/components/Footer/FooterLinks.js
- naurffxiv/src/components/Footer/FooterSocialLinks.js
- naurffxiv/src/components/Homepage/HomepageContent.js
- naurffxiv/src/components/Mdx/MdxContent.jsx
- naurffxiv/src/components/NavBar/NavBar.js
Ticket: NAUR-78
Fixes the FOUC in the homepage (and hopefully in other potential areas too)
Also minor redo of alignment and spacing for the little icons + descriptions on the homepage
> Fix flash of unstyled content + minor homepage content fix

- naurffxiv/src/components/Footer/Footer.js
Ticket: NAUR-81
Dependent on #78 
Adjusts footer disclaimer's styles slightly
> Adjust footer disclaimer's styles

- naurffxiv/src/app/layout.js
> Implement goatcounter

- naurffxiv/src/app/constants.js
- naurffxiv/src/components/Footer/FooterSocialLinks.js
- naurffxiv/src/components/NavBar/NavBar.js
Ticket: NAUR-80
- Hide events and staff links in footer and nav bar
- Add Findingway link to navbar and footer
- Update footer ultimate links
- Add links to discord. github repo, and pateron images
> Update Links and Hide non-initial release items

- naurffxiv/src/components/Footer/Footer.js
> Ensure footer is centered for larger resolutions

- naurffxiv/src/markdown/ultimates/fru.mdx
> Fix double "Crystalize Time" typo

- naurffxiv/src/components/NavBar/NavBar.js
Ticket: NAUR-93
Requested by Rem to remove navbar
> Remove github from navbar

- naurffxiv/src/components/Homepage/Offerings.js
Ticket: NAUR-97
Change descriptions to be more clear and defined.
> Change home page descriptions to be more clear and defined

- naurffxiv/src/app/globals.css
- naurffxiv/src/components/Homepage/Hero.js
- naurffxiv/tailwind.config.js
> Set max width for hero and adjust style for wider resolutions

- naurffxiv/src/components/Homepage/FightGuideList.js
- naurffxiv/src/components/Homepage/Hero.js
- naurffxiv/src/components/Homepage/HomepageContent.js
- naurffxiv/src/components/Homepage/OfferingCards.js
- naurffxiv/tailwind.config.js
Ticket: NAUR-106
Adjusts some colors for the homepage and offering content
> Adjust homepage's styles + content

- naurffxiv/src/components/Mdx/MdxComponents.js
- naurffxiv/src/components/Video/Streamable.js
- naurffxiv/src/components/Video/TwitchClip.js
- naurffxiv/src/components/Video/TwitchVoD.js
- naurffxiv/src/components/Video/YouTube.js
- naurffxiv/src/markdown/example.mdx
Ticket: NAUR-101
Dependent on #98
Implements components for embedded videos from various sources. 
Each component can have the following attributes:
- `videoId` (required)
- `width`
- `height`
- `className`
URL: https://www.youtube.com/watch?v=mLgSYUQbKHc
videoId: `mLgSYUQbKHc`
URL: https://www.twitch.tv/videos/2149278406?filter=highlights&sort=time
videoId: `2149278406`
URL: https://www.twitch.tv/jerma985/clip/KnottyOddFishShazBotstix?filter=clips&range=all&sort=time
videoId: `KnottyOddFishShazBotstix`
> Implement Youtube, Twitch VoD, and Twitch Clip components

- src/app/layout.js
Ticket: NAUR-119
This PR stops goat counter from tracking previews of branch deploys/deploy previews
> Disable tracking of goat counter views on previews

- next.config.mjs
Ticket: NAUR-132
This PR redirects anybody who accesses /ultimates to /ultimate to keep old links working
> Redirect /ultimates to /ultimate

- src/app/constants.js
- src/markdown/extreme/_meta.json
- src/markdown/extreme/guides/sphenes-burden_guide.mdx
- src/markdown/extreme/sphenes-burden.mdx
- src/markdown/savage/_meta.json
- src/markdown/savage/guides/m2s_guide.mdx
- src/markdown/savage/guides/m3s_guide.mdx
- src/markdown/savage/guides/m4s_guide.mdx
- src/markdown/savage/m1s.mdx
- src/markdown/savage/m2s.mdx
- src/markdown/savage/m3s.mdx
- src/markdown/savage/m4s.mdx
- src/markdown/ultimate/_meta.json
> Group pages into respective expansion or tier

- src/markdown/ultimate/_meta.json
Ticket: NA
oops, somehow overlooked this
> Fix DSR guide page mapping

- src/app/constants.js
> Fix typo in navbar

- src/app/constants.js
- src/components/Footer/Footer.js
- src/components/Footer/FooterLinks.js
- src/components/Homepage/FightGuideList.js
- src/components/NavBar/ContentDropdown.js
Ticket: NAUR-156
This PR refactors the repetitive information in `constants.js`.
Each component that uses some information, the navbar dropdowns, footer, and fight guide list, all had separate lists defined for what is essentially the same overall info, which results in the need to change the same value in multiple places instead of just one. I've combined all of the components' lists into one (for each difficulty/category) to better reuse the same info.
> Refactor repetitive information in constants.js

- README.md
- package-lock.json
- package.json
prettier wanted to change ever file for some reason, this PR really only changes the intial readme
> Move readme to wiki

- src/components/Common/ExitButton.js
- src/components/Mdx/Layout/MobileDrawer.js
> Add mobile quick links drawer exit button

- src/app/(protected)/mod-portal/active-exiles/page.tsx
- src/app/(protected)/mod-portal/layout.tsx
- src/app/(protected)/mod-portal/notes/page.tsx
- src/app/(protected)/mod-portal/page.js
- src/app/(protected)/mod-portal/page.tsx
- src/app/(protected)/mod-portal/settings/page.js
- src/app/(protected)/mod-portal/settings/page.tsx
- src/app/(protected)/mod-portal/strikes/page.tsx
- src/app/(protected)/mod-portal/unban-appeals/page.tsx
Fixes several lint checks that are polluting the PR diffs
> Lint Return Type Checks

- src/markdown/ultimate/uwu.mdx
Closes https://github.com/naurffxiv/naurffxiv/issues/235
> Update Garuda + Predation Toolbox

- src/markdown/ultimate/top.mdx
> Fix formatting pipeline

- src/markdown/ultimate/top.mdx
Closes #260
This PR fixes the bug of the banner and a couple links in P1 and P4 showing twice - pointing directly to main.
> Fix TOP page duplication

- src/config/constants.ts
- src/markdown/extreme/_meta.json
- src/markdown/extreme/ageless-necropolis.mdx
Updated EX5 info with correct name and Hector information.
> 273 import guide for ex 5
